# -*- coding: utf-8 -*-
"""Loops-19_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tp58FmLte_XMsFJaHanW8tR3gie-nSM
"""

# write a program for check entered number is armstrong or not

# write a program for calculate the digit of number

x = int(input("Enter the number for check number is armstrong or not : "))
original = x
count =0
total_add = 0
for i in str(x):
  count+=1
for i in str(x):
  i = int(i)
  i = pow(i,count)
  total_add = total_add+i
if original == total_add:
  print("number is arm strong")
else:
  print("number is not arm strong")

no = int(input("Enter the numebr : "))
i = 1
fact = 1
while i<=no:
  fact *= i

print(fact)

# wap for calculate the lcm of two number  ?
#step1 : take two number as input
# step 2 : maximum calculate
# step 3 : divide maximum by num1 and num2
num1 = int(input("Enter the number 1 : "))
num2 = int(input("Enter the number 2 : "))
max = num1 if (num1>num2) else num2
i=1
while True:
  if max%num1 ==0 and max %num2 ==0:
    print("LCM : ",max)
    break
  else:
    i+=1

    max = max*1

