# -*- coding: utf-8 -*-
"""String

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZI4qck4Voyksv_mb_Exf-ogMxN9bEK3
"""

text = "CDGI"
print(text.zfill(5))

text = "akash"
table = str.maketrans("a","आ")
print(text.translate(table))

text = "      akash      "
print(text.strip())

# startswith()

text = "akash\ntiwari"
print(text.splitlines())
print(text)

!pip install googletrans==4.0.0-rc1

from googletrans import Translator

